### PR TITLE
[ECO-5122] Implement the "asynchronously" part of CHA-RL1h5

### LINKED ISSUE #119: Implement "asynchronously" part of CHA-RL1h5
Split from #28

CHA-RL1h5 says that the detaching of all non-failed channels should happen "asynchronously with respect to CHA-RL1h4" (in my current implementation, it happens as part of the `ATTACH` operation, thus not fulfilling this spec point)

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/ECO-5122) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
**Note: This PR is based on top of #171; please review that one first.**

Note that CHA-RL1h5, as currently written, does not respect operation atomicity. I’ve raised https://github.com/ably/specification/issues/253 for this, and my implementation implements the changes that I’ve suggested there, introducing a new `RUNDOWN` room lifecycle operation. See commit messages and code comments for more details.

Resolves #119.

## Summary by CodeRabbit

- **New Features**
	- Introduced a `RUNDOWN` operation for improved room lifecycle management, allowing for better handling of failed contributors.
	- Enhanced status management with new operational states for more robust error handling during attach and detach processes.

- **Bug Fixes**
	- Improved the retry logic for detaching contributors when a failure occurs.

- **Documentation**
	- Updated comments and documentation for clarity on new operations and their integration within the lifecycle management.

### CODE REVIEW

**Comment by lawrence-forooghian** [comment]
Tests are failing due to https://github.com/ably/ably-chat-swift/issues/169.

**Comment by maratal** [comment]
What does this mean @lawrence-forooghian:

`When the room enters the FAILED status as a result of CHA-RL1h4, asynchronously with respect to CHA-RL1h4 ...`

**Comment by lawrence-forooghian** [comment]
Yeah, that spec point isn't very clear; I hope that we can also make it clearer when we address https://github.com/ably/specification/issues/253. My interpretation is that it means something like:

> When the room enters the `FAILED` status as a result of `CHA-RL1h4`, then the room will detach all channels that are not in the `FAILED` state. It will perform this detach in a manner that does not block the completion of the `ATTACH` operation.

**Comment by maratal** [comment]
> Yeah, that spec point isn't very clear; I hope that we can also make it clearer when we address [ably/specification#253](https://github.com/ably/specification/issues/253). My interpretation is that it means something like:
> 
> > When the room enters the `FAILED` status as a result of `CHA-RL1h4`, then the room will detach all channels that are not in the `FAILED` state. It will perform this detach in a manner that does not block the completion of the `ATTACH` operation.

But they all `async` anyway. Also attach operation is failed at this point and all you need to do is to detach all the channels. So I still don't get it.

**Comment by lawrence-forooghian** [comment]
> But they all async anyway.

What do you mean?

> Also attach operation is failed at this point 

You mean because CHA-RL1h4 says that the `ATTACH` operation should throw an error and enter `FAILED`? Yeah, but before this "asynchronous" part was added to CHA-RL1h5, it wasn't clear at what moment the CHA-RL1h5 detach was meant to happen — e.g. maybe it was between the `FAILED` status change and the completion of the `ATTACH` operation

**Comment by maratal** [comment]
> > But they all async anyway.
> 
> What do you mean?

It was re "_in a manner that does not block_", but is nonsense anyway, ignore.

> > Also attach operation is failed at this point
> 
> You mean because CHA-RL1h4 says that the `ATTACH` operation should throw an error and enter `FAILED`? Yeah, but before this "asynchronous" part was added to CHA-RL1h5, it wasn't clear at what moment the CHA-RL1h5 detach was meant to happen — e.g. maybe it was between the `FAILED` status change and the completion of the `ATTACH` operation

So attach operation might complete (failed) before channels are detached? What state room is between it goes to FAILED and all channels are detached?

**Comment by lawrence-forooghian** [comment]
> So attach operation might complete (failed) before channels are detached?

Yep.

> What state room is between it goes to FAILED and all channels are detached?

It remains `FAILED`.

File: Sources/AblyChat/RoomLifecycleManager.swift [hunk 1]
```diff
@@ -216,6 +219,10 @@ internal actor DefaultRoomLifecycleManager<Contributor: RoomLifecycleContributor
                 .suspended(error: error)
             case let .suspended(_, error):
                 .suspended(error: error)
+            case let .failedAwaitingStartOfRundownOperation(_, error):
+                .failed(error: error)
+            case let .failedAndPerformingRundownOperation(_, error):
+                .failed(error: error)
```
Comment (maratal) [inline Sources/AblyChat/RoomLifecycleManager.swift:225]: https://github.com/ably/ably-chat-swift/pull/174#issuecomment-2521332125

>It remains FAILED.

It's here between L223 and 225, right?

**Review by maratal — APPROVED** [review]
LGTM

File: Sources/AblyChat/RoomLifecycleManager.swift (hunk 1 above)
Comment (lawrence-forooghian) [reply Sources/AblyChat/RoomLifecycleManager.swift:225]: Not sure I understand the question. 

> What state room is between it goes to FAILED and all channels are detached?

the manager goes through the following statuses:

- during the `ATTACH` operation, before the `RUNDOWN` operation starts: `failedAwaitingStartOfRundownOperation`
- once the `RUNDOWN` operation starts: `failedAndPerformingRundownOperation`
- once the `RUNDOWN` operation completes (i.e. all channels have been detached): `failed`

(all of these manager statuses map to the `failed` room status)
